### ISSUE TITLE
Improve JSON Deserialization Performance

### ISSUE THREAD

**Issue by robertlong** [robertlong/UnityGLTFLoader#10]
Currently JSON deserialization is a bit slow and not concurrent. It blocks the renderer and causes dropped frames. I'd like to move it to another thread or at least make it concurrent. There's also likely a lot of room for improvement in overall parsing speed.

**Comment by robertlong** [comment]
Performance greatly improved via manual deserialization in https://github.com/robertlong/UnityGLTFLoader/commit/db40b19589113500becf90650c95d755c9e54b48

Previously we were using JSON.NET's [JsonConvert.DeserializeObject](http://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_JsonConvert_DeserializeObject__1.htm) which uses reflection to deserialize the provided object.

I've moved everything to manual deserialization which removes all reflection and really speeds things up.

Sample Model | Reflection Parse Time | Reflection GCAlloc | Manual Parse Time | Manual GCAlloc |
------------ | ------------- | ---------- | ---------- | ----------
Lantern | 389.40ms | 7.6MB | 31.56ms | 99.6KB |
Corset | 377.99ms | 7.8MB | 29.36ms | 55.7KB |
BoomBox | 384.86ms | 7.8MB | 29.29ms | 85KB |

There's probably still a lot more room for performance improvements, but I'm feeling pretty good about our parsing performance now.

**Comment by stevenvergenz** [comment]
Wow, that's some intense savings. Nicely done!

**Comment by donmccurdy** [comment]
Any idea why parsing here would be slower than JSON parsing in e.g. the browser? All three of the sample models above take ~3ms with `JSON.parse()` in Firefox, or 10x faster.. I suppose that's partly because the C# is processing the model into structured objects and typed values, whereas JS is looser about this?
