### ISSUE TITLE
Consider submitting this project to the spec list of implementers

### ISSUE THREAD

**Issue by stevenvergenz** [robertlong/UnityGLTFLoader#11]
The Khronos Group has a call out for open-source projects that implement the spec: https://github.com/KhronosGroup/glTF/issues/867. You should consider submitting this project, you might get more help.

**Comment by stevenvergenz** [comment]
Oh, you're already on the list. Consider this done :)

**Comment by robertlong** [comment]
Yeah, @pjcozzi added me. Thanks!
