### ISSUE TITLE
Error when playing a scene that tried to load a binary

### ISSUE THREAD

**Issue by Hugo-Pereira** [robertlong/UnityGLTFLoader#16]
Works fine for non-binary glTF, however all of the binary scenes print this error:

```
ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
System.Buffer.BlockCopy (System.Array src, Int32 srcOffset, System.Array dst, Int32 dstOffset, Int32 count) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Buffer.cs:112)
GLTF.GLTFLoader+<LoadImage>c__Iterator4.MoveNext () (at Assets/GLTF/Scripts/GLTFLoader.cs:574)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
```

Am I doing something wrong?

**Comment by robertlong** [comment]
I've seen that bug with models in the past, but I thought I fixed it. Could you update to the latest master and run the Integration tests?

To do that you first need to open up the `IntegrationTestScene`. Then open Unity Test Tools -> Integration Test Runner. And finally click run all.

Right now I know AnimatedCubeTest, MetalRoughSpheresTest, NormalTangentTest, and ScifiHelmetTest are failing for various reasons. Let me know if you see something different.

Thanks!

**Comment by Hugo-Pereira** [comment]
Can't run the tests as I get these errors:
`UNetWeaver error: Exception :System.MissingMethodException: Method not found: 'Mono.Cecil.ModuleDefinition.ImportReference'.
  at Unity.UNetWeaver.Weaver.Weave (System.String assName, IEnumerable`1 dependencies, IAssemblyResolver assemblyResolver, System.String unityEngineDLLPath, System.String unityUNetDLLPath, System.String outputDir) [0x0004b] in C:\buildslave\unity\build\Extensions\Networking\Weaver\UNetWeaver.cs:1713 
  at Unity.UNetWeaver.Weaver.WeaveAssemblies (IEnumerable`1 assemblies, IEnumerable`1 dependencies, IAssemblyResolver assemblyResolver, System.String outputDir, System.String unityEngineDLLPath, System.String unityUNetDLLPath) [0x0006e] in C:\buildslave\unity\build\Extensions\Networking\Weaver\UNetWeaver.cs:1837 
UnityEngine.Debug:LogError(Object)
Unity.UNetWeaver.Log:Error(String) (at C:/buildslave/unity/build/Extensions/Networking/Weaver/Program.cs:20)
Unity.UNetWeaver.Weaver:WeaveAssemblies(IEnumerable`1, IEnumerable`1, IAssemblyResolver, String, String, String) (at C:/buildslave/unity/build/Extensions/Networking/Weaver/UNetWeaver.cs:1844)
Unity.UNetWeaver.Program:Process(String, String, String, String[], String[], IAssemblyResolver, Action`1, Action`1) (at C:/buildslave/unity/build/Extensions/Networking/Weaver/Program.cs:34)
UnityEditor.Scripting.Serialization.Weaver:WeaveUnetFromEditor(String, String, String, String, Boolean)
`
`Failure generating network code.
UnityEditor.Scripting.Serialization.Weaver:WeaveUnetFromEditor(String, String, String, String, Boolean)
`
I should have mentioned that I am using the latest Unity version, 5.5.0f3

**Comment by robertlong** [comment]
I found this: https://issuetracker.unity3d.com/issues/unetweaver-error-after-upgrading-project-from-5-dot-4-to-5-dot-5-slash-5-dot-6

I've updated Unity Test Tools in the latest commit to master. Could you pull and try again?

**Comment by Hugo-Pereira** [comment]
Everything works now! Thanks a bunch this will be helpful for my next project 👍

**Comment by robertlong** [comment]
Glad to hear it!
